name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Start with Docker Compose
        run: docker compose -f infrastructure/docker-compose.yml up -d --build
